[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bitbank2/PNGdec@^1.1.6
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit ILI9341@^1.6.3
	bblanchon/ArduinoJson@^7.4.3
	adafruit/Adafruit FT6206 Library@^1.1.1
	olikraus/U8g2@^2.36.18
	olikraus/U8g2_for_Adafruit_GFX@^1.8.0